version: '3.1'
services:
  stats-server:
    build: ./statistics-service/statistics-server
    container_name: statistics-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistics-db:5432/statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "5432:5432"
    volumes:
      - stats-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  main-service:
    build: ./main-service/main-server
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/mainservice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "5433:5432"
    volumes:
      - main-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mainservice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
volumes:
  stats-db:
  main-db: