version: '3.1'
services:
  stats-server:
    build: ./statistics-service/statistics-server
    container_name: statistics-server
    ports:
      - "9090:9090"
    depends_on:
      - statistics-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistics-db:5432/statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "6541:5432"
    volumes:
      - stats-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  stats-db: